--- 
abstract: An image viewer in Perl::Tk based on IrfanView
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.132510
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-tkiv
optional_features: 
  opt_format_tiff: 
    description: Support for TIFF
    requires: 
      Tk::TIFF: 0
  opt_xeleven_protocol: 
    description: Use X11::Protocol to get the screen size
    requires: 
      X11::Protocol: 0
provides: 
  App::tkiv: 
    file: lib/App/tkiv.pm
    version: '0.125'
recommends: 
  Getopt::Long: '2.41'
  Test::More: '0.98'
  Tk: '804.031'
  perl: '5.018001'
requires: 
  Data::Peek: 0
  File::Copy: 0
  Getopt::Long: '2.27'
  Image::ExifTool: 0
  Image::Info: 0
  Image::Size: 0
  Test::Harness: 0
  Test::More: '0.88'
  Tk: '804.027'
  Tk::Animation: 0
  Tk::Balloon: 0
  Tk::Bitmap: 0
  Tk::BrowseEntry: 0
  Tk::Dialog: 0
  Tk::DirTree: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  Tk::Pane: 0
  Tk::Photo: 0
  Tk::Pixmap: 0
  perl: '5.010'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/App-tkiv.git
version: '0.125'
